In [2]:
import numpy as np

lst = [1,2,3,4,5]
ar = np.array(lst)
ar

tup = (1,2,3,4,5)
ar = np.array(tup)
ar

In [10]:
lst = [[1,2,3],[3,4,5]]
ar = np.array(lst)
ar

array([[1, 2, 3],
       [3, 4, 5]])

In [18]:
lst = [1,2,3,44444]
ar = np.array(lst,dtype = 'U')
ar

array(['1', '2', '3', '44444'], dtype='<U5')

In [17]:
ar = np.array(lst,dtype = '<U2')
ar

array(['1', '2', '3', '44'], dtype='<U2')

In [25]:
a = np.zeros([3,2])
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
a = np.ones((2,3,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [41]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
b = a.reshape(2,3,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [46]:
c = b.reshape(12)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
a = np.arange(0,13,3)
a

array([ 0,  3,  6,  9, 12])

In [51]:
f = np.arange(15).reshape(3,5)
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
f.ndim

2

In [53]:
f.shape

(3, 5)

In [54]:
f.size

15

In [55]:
f.dtype

dtype('int32')

In [56]:
f.itemsize

4