In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [23]:
a[2:5:2][1]

4

In [26]:
a[::-1][2:4]

array([3, 2])

In [28]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
b[2,2]

12

In [40]:
b[0:2,2:4]

array([[2, 3],
       [7, 8]])

In [41]:
b[2,:]

array([10, 11, 12, 13, 14])

In [42]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### 一维数组的组合

In [46]:
a = np.arange(1,4)
a

array([1, 2, 3])

In [48]:
b = np.arange(5,8)
b

array([5, 6, 7])

In [52]:
c = np.concatenate([a,b,[4,3,4,5]])
c

array([1, 2, 3, 5, 6, 7, 4, 3, 4, 5])

In [53]:
v = np.vstack((a,b))
v

array([[1, 2, 3],
       [5, 6, 7]])

In [54]:
h = np.hstack((a,b))
h

array([1, 2, 3, 5, 6, 7])

In [119]:
m,n = np.vsplit(v,[1])

In [120]:
m

array([[1, 2, 3]])

In [121]:
n

array([[5, 6, 7]])

In [115]:
x,y = np.hsplit(h,[3])

In [116]:
x

array([1, 2, 3])

In [117]:
y

array([5, 6, 7])

### 数组的+ - * / 运算

In [122]:
v

array([[1, 2, 3],
       [5, 6, 7]])

In [123]:
v + 1

array([[2, 3, 4],
       [6, 7, 8]])

In [124]:
v * 2

array([[ 2,  4,  6],
       [10, 12, 14]])