In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [4]:
a + b

array([5, 7, 9])

In [5]:
a - b

array([-3, -3, -3])

In [6]:
a * b

array([ 4, 10, 18])

In [8]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
y = x + 2
y

array([[3, 4, 5],
       [6, 7, 8]])

In [10]:
x + y

array([[ 4,  6,  8],
       [10, 12, 14]])