### 1、爬取前需要明确的几个问题

#### 1.1API请求的URL地址
矩形区域检索
http://api.map.baidu.com/place/v2/search?query=银行&bounds=39.915,116.404,39.975,116.414&output=json&ak={您的密钥} //GET请求

#### 1.2网络大小相关尺寸
> 1度：约等于111km，则0.1度约等于11km  
> 0.05度方格面积约为：5.5km *5.5km  = 30.25km^2  
> 0.02度方格面积约为 2.2km * 2.2km = 5km^2  

http://lbsyun.baidu.com/index.php?title=lbscloud/poitags  
http://lbsyun.baidu.com/index.php?title=webapi/guide/webservice-placeapi

范围（百度坐标）：108.756009,34.16985,109.146952,34.395586

### 2、网格划分

#### 2.1经纬度切割

In [81]:
import numpy as np

In [7]:
a = 39.32
b = 39.53
ls = [str(b)]
while a < b:
    m = b - 0.02
    ls.append('%.2f' % m)
    b = m
print(sorted(ls))

['39.31', '39.33', '39.35', '39.37', '39.39', '39.41', '39.43', '39.45', '39.47', '39.49', '39.51', '39.53']


In [80]:
class LocaDiv(object):
    #创建初始化参数
    def __init__(self,loc_all,divd):
        self.loc_all =  loc_all
        self.divd = divd
        
    #获取以divd分割的每个维度列表
    def lat_all(self):
        bl_lat = self.loc_all[0]
        ur_lat = self.loc_all[2]
        ls = [str(ur_lat)]
        while bl_lat < ur_lat:
            m = ur_lat - self.divd
            ls.append('%.2f' % m)
            ur_lat = m
        return sorted(ls)

    #获取以divd分割的每个经度列表
    def lng_all(self):
        bl_lng = self.loc_all[1]
        ur_lng = self.loc_all[3]
        ls = [str(ur_lng)]
        while bl_lng < ur_lng:
            m = ur_lng - self.divd
            ls.append('%.2f' % m)
            ur_lng = m
        return sorted(ls)
    
    #依次组合每个方格左下到右上的点
    def com_coor(self):
        lat_lst = self.lat_all()
        lng_lst = self.lng_all()
        lst = []
        for i in range(len(lat_lst)-1):
            for j in range(len(lng_lst)-1):
                lst.append(lat_lst[i])
                lst.append(lng_lst[j])
                lst.append(lat_lst[i+1])
                lst.append(lng_lst[j+1]) 
        arr = np.array(lst).reshape(len(a)//4,4)
        return arr
    
        
if __name__ == "__main__":
    coor = [1,1,3,4]#bl_lat,bl_lng,ur_lat,ur_lng
    loc = LocaDiv(coor,1)
    print(loc.lng_all())
    print(loc.lat_all())
    print(loc.com_coor())
    
        

['1.00', '2.00', '3.00', '4']
['1.00', '2.00', '3']
[['1.00' '1.00' '2.00' '2.00']
 ['1.00' '2.00' '2.00' '3.00']
 ['1.00' '3.00' '2.00' '4']
 ['2.00' '1.00' '3' '2.00']
 ['2.00' '2.00' '3' '3.00']
 ['2.00' '3.00' '3' '4']]


In [29]:
def lat_all(coor,divd):
    a = coor[0]
    b = coor[2]
    ls = [str(b)]
    while a < b:
        m = b - divd
        ls.append('%.2f' % m)
        b = m
    return sorted(ls)

coor = [1,1,4,5]
divd = 1
a = lat_all(coor,divd)
print(a)

['1.00', '2.00', '3.00', '4']


In [32]:
import numpy as np

In [63]:
a = numpy.arange(12).reshape(3,4)
print(a)
b = a[::-1]
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [69]:
lst = ['1.00', '1.00', '2.00', '2.00', '1.00', '2.00', '2.00', '3.00', '1.00', '3.00', '2.00', '4', '2.00', '1.00', '3', '2.00', '2.00', '2.00', '3', '3.00', '2.00', '3.00', '3', '4']
a = numpy.array(lst)
a

array(['1.00', '1.00', '2.00', '2.00', '1.00', '2.00', '2.00', '3.00',
       '1.00', '3.00', '2.00', '4', '2.00', '1.00', '3', '2.00', '2.00',
       '2.00', '3', '3.00', '2.00', '3.00', '3', '4'], dtype='<U4')

In [75]:
len(a)//4

6

In [79]:
a.reshape(len(a)//4,4)[1]

array(['1.00', '2.00', '2.00', '3.00'], dtype='<U4')